name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag apiservice:latest
    - name: Update latest tag
      run: docker tag registry.digitalocean.com/ltpreviews/apiservice
    - name: Update registry for automaic deployment
      run: docker push registry.digitalocean.com/ltpreviews/apiservice
